### ISSUE TITLE
Select all fields?

### ISSUE THREAD

**Issue by alexturpin** [mzalevski/postgrest-js-tools#1]
Great project! Super useful to get better types with Supabase.

One suggested feature could be select all fields from a foreign relation.

For instance, if I want only a few fields from my main table, but all the fields from the foreign relation, I could do;¸

```ts
const shape = getShape<Post>()({
  id: true,
  title: false, // if value === false then we skip the key
  user: { _: "user_id", "*": true },
});
```

**Comment by mzalevski** [comment]
Sounds good. I'll look into it :)

**Comment by mzalevski** [comment]
Getting the types alone is feasible, because we do have all the type information. Nevertheless, getting the fields string is not. You see, in the runtime JS knows only of the object fields we explicitly passed in the argument. Unfortunately the only way around this is using some kind of runtime reflection system. This would add immense complexity to the package. It's just not worth it.

Thanks again for the suggestion.

**Comment by alexturpin** [comment]
> Getting the types alone is feasible, because we do have all the type information. Nevertheless, getting the fields string is not. You see, in the runtime JS knows only of the object fields we explicitly passed in the argument. Unfortunately the only way around this is using some kind of runtime reflection system. This would add immense complexity to the package. It's just not worth it.
> 
> Thanks again for the suggestion.

@mzalevski thanks for looking into it!

Just to clarify, do you mean getting the fields string to pass to the `select` function? I believe we can use the `*` operator for that. For instance, in the example of my post, that string could be generated as `id,title,user(*)`.

**Comment by mzalevski** [comment]
@alexturpin oh, you are right. I totally forgot about passing the `*`. It comes down to the types then. I will try to make it work :)

**Comment by mzalevski** [comment]
@alexturpin I've just [released](https://github.com/mzalevski/postgrest-js-tools/releases/tag/v1.1.0) a new version with this feature! Please upgrade to v1.1.0 and give it a try :)

**Comment by alexturpin** [comment]
@mzalevski that's fantastic! Thank you so much 🙏
