### ISSUE TITLE
Supporting n:m relationships

### ISSUE THREAD

**Issue by paullyFIRE** [mzalevski/postgrest-js-tools#5]
Very cool lib!

Would be amazing if it could support n:m relationships, if not already possible.

**Comment by mzalevski** [comment]
Thanks @paullyFIRE. It's not really possible at the moment. The types get messed up. Although it seems to be easy to make it work. I will prepare a PR in a day or so :)

**Comment by mzalevski** [comment]
@paullyFIRE this is now supported. Update to the [v1.2.0](https://github.com/mzalevski/postgrest-js-tools/releases/tag/v1.2.0) :)
